### ISSUE TITLE
Update utils.py

### ISSUE THREAD

**Issue by ch4rli3kop** [ssl3rd-svd/binja-snippets#2]
기존 utils에 추가한 evaluation 관련 기능을 helper class로 확장할 필요성이 있음.

현재 사용하고 있는 testcase에서는 각 바이너리당 하나의 취약점을 가지고 있어 매우 단순한 코드(단순 리스트를 비교)로 구현되어 있지만, 추후 바이너리가 복수의 취약점을 갖는 경우를 생각하면, 각각의 취약점을 구분하기 위한 기능을 고려할 필요가 있음.

또한, 효율적인 관리를 위해 통계를 계산하는 기능을 고려한다면, 모든 바이너리의 테스트를 관리하기 위한 클래스 설계가 필수적으로 보임.

**Comment by ch4rli3kop** [comment]
bad function을 판단하는 것도 현재 regex로 함수 이름이 _CWE로 시작하고 bad로 끝나는 패턴으로 매칭하게 되어 있는데, badsink 가 있는 경우 해당 경우를 bad function으로 선택하도록 추가해야 함.

**Comment by kiddo-pwn** [comment]
badsink 가 있는 경우 re.match 함수 대신 re.fullmatch 함수 사용해서
`bad_functions = [func for func in bv.functions if re.fullmatch('CWE.*_bad', func.name)]`와 같이 사용하면 유용할 듯 합니다.

**Comment by kiddo-pwn** [comment]
get_all_files_from_path 함수 같은 경우도 `get_matched_files_from_path`같이 전체 디렉토리에서 특정 패턴('CWE78_OS_Command_Injection__char_console_*')만 뽑을 수 있는 식으로 구현하면 특정 유형 바이너리만 빼올 수 있을 것 같아 추가하면 괜찮을 것 같습니다.

**Comment by ch4rli3kop** [comment]
Runner class 추가 완료 #11 

가칭 Binary Class를 따로 만들어서 Runner class 에서 관리하는 것도 좋을 것 같음.
Binary Class 내에서 C와 C++ 바이너리를 구분해서 bad function을 찾는 식으로 코드를 구성하면 더 깔끔할 것 같음.

또한 bof 등의 flow를 형성하는 취약점의 경우 badSource부터 badSink까지 function 객체가 연결된 그래프 형태로 다루는 것이 좋아보이는데, 이 작업을 Binary class에서 처리하면 좋을 듯함.
